### ISSUE TITLE
Shortcut command not showing

### ISSUE THREAD

**Issue by ChrisFiftyTwo** [Qwyntex/doubleshift#15]
Cant see what command each assigned shotcut/hotkey is assigned to:

![image](https://user-images.githubusercontent.com/59583896/207686268-bdf250c3-56ce-41de-9d72-eac3c69b7307.png)

**Comment by Qwyntex** [comment]
I am sorry I must have missed this issue. The command can be seen when hovering over the select command button. This is because different commands have different lengths that, in some cases, vary vastly. So to remove visual clutter I have chosen not to show the commands. If you have ideas to improve this feel free to suggest them.
